[project]
name = "tidy-tuesday"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "pydytuesday>=0.0.4",
    "requests>=2.32.3",
]
